# Generated by Django 3.1.4 on 2021-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=64, unique=True)),
                ('ing_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ing_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ing_photo', models.ImageField(upload_to='images/')),
                ('ing_foodgroup', models.CharField(choices=[('f & v', 'Fruit and vegetables'), ('carbs', 'Carbohydrates'), ('proteins', 'Proteins'), ('dairy', 'Dairy'), ('fats and oils', 'Fats and oils')], max_length=64)),
                ('ing_dietarygroup', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('pescatarian', 'Pescatarian')], max_length=64)),
                ('ing_description', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
