# Generated by Django 3.1.4 on 2021-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_ingrediant_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediant',
            name='ing_photo',
            field=models.FileField(max_length=254, upload_to='images/'),
        ),
    ]
