# Generated by Django 3.1.4 on 2021-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_auto_20210219_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediant',
            name='ing_foodgroup',
            field=models.CharField(choices=[('f & v', 'Fruit and vegetables'), ('carbs', 'Carbohydrates'), ('proteins', 'Proteins'), ('dairy', 'Dairy'), ('fats & oils', 'Fats and oils')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ingrediant',
            name='ing_photo',
            field=models.ImageField(max_length=254, upload_to='images/'),
        ),
    ]
