# Generated by Django 3.1.4 on 2021-02-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_auto_20210223_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediant',
            name='ing_dietarygroup',
            field=models.CharField(choices=[('VE', 'Vegan'), ('VTRN', 'Vegetarian'), ('HLL', 'Halal'), ('KSH', 'Kosher'), ('PSC', 'Pescatarian')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ingrediant',
            name='ing_foodgroup',
            field=models.CharField(choices=[('FR', 'Fruits'), ('VEGT', 'Vegetable'), ('CARBS', 'Carbohydrate'), ('PROT', 'Protein'), ('DARY', 'Dairy'), ('FT', 'Fats'), ('OL', 'Oils')], max_length=64),
        ),
    ]
