# Generated by Django 3.1.4 on 2021-03-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0005_auto_20210223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediant',
            name='ing_photo',
            field=models.ImageField(max_length=254, null=True, upload_to='images/'),
        ),
    ]
